"""fix sub.teacher_id

Revision ID: 8e5b527043be
Revises: 0b7e128ed4ac
Create Date: 2023-11-03 10:15:49.952357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e5b527043be'
down_revision: Union[str, None] = '0b7e128ed4ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('teacher_id', sa.Integer(), nullable=True))
    op.drop_constraint('subjects_group_id_fkey', 'subjects', type_='foreignkey')
    op.create_foreign_key(None, 'subjects', 'teachers', ['teacher_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('subjects', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.create_foreign_key('subjects_group_id_fkey', 'subjects', 'teachers', ['group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('subjects', 'teacher_id')
    # ### end Alembic commands ###
